apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Graphite
    uid: graphite
    type: graphite
    access: proxy
    url: http://graphite
    editable: false
